### ISSUE TITLE
Bug/Typo in frequency decoding in the node

### ISSUE THREAD

**Issue by fcolas** [RCPRG-ros-pkg/RCPRG_laser_drivers#1]
Hi Konrad,

In the lib, the frequency is expressed in 1/100 of Hz in the scanCfg object.
However, at the initialization of the message the scan_time is computed by assuming 1/1000th of Hz.
The consequence is that both scan_time and time_increment values are 10 times too large in the ROS message.
The fix is simple:

```
--- LMS1xx_node.cpp.orig    2011-08-17 11:23:16.000000000 +0200
+++ LMS1xx_node.cpp 2011-08-17 11:23:25.000000000 +0200
@@ -43,7 +43,7 @@
     scan_msg.range_min = 0.01;
     scan_msg.range_max = 20.0;

-    scan_msg.scan_time = 1000.0/cfg.scaningFrequency;
+    scan_msg.scan_time = 100.0/cfg.scaningFrequency;

     scan_msg.angle_increment = cfg.angleResolution/10000.0 * DEG2RAD;
     scan_msg.angle_min = cfg.startAngle/10000.0 * DEG2RAD - M_PI/2;
```

Cheers,
## 

Francis

**Comment by konradb3** [comment]
fixed.
