### ISSUE TITLE
Catkin

### ISSUE THREAD

**Issue by NCharabaruk** [RCPRG-ros-pkg/RCPRG_laser_drivers#3]
Has this been updated to work with catkin as stated by the ros wiki page?

**Comment by konradb3** [comment]
No it's still using rosbuild.
Where ros wiki states that this was converted to catkin ?

**Comment by NCharabaruk** [comment]
On http://ros.org/wiki/LMS1xx at the top it shows both fuerte and groovy. As groovy uses catkin, if it doesn't use catkin then there shouldn't be a tab for groovy. I tried to use catkin to install this but it didn't work, which is why I am asking.

**Comment by konradb3** [comment]
Yes, but groovy support both catkin and rosbuild. There is still many packages in groovy which use rosbuild.

**Comment by NCharabaruk** [comment]
Oh. Excellent. I just started using ROS, so I am still getting the hang of it. I thought with groovy you had to use catkin. Thanks for the info.
