### ISSUE TITLE
Problem with building the package

### ISSUE THREAD

**Issue by NCharabaruk** [RCPRG-ros-pkg/RCPRG_laser_drivers#4]
I am new to ROS, so excuse me if I am missing something obvious. I am getting an error when using rosmake to build this package. The terminal says "[ rosmake ] Halting due to failure in package libLMS1xx." When I look in the log it says 
"git clone http://github.com/konradb3/libLMS1xx.git build/libLMS1xx
fatal: could not create leading directories of 'build/libLMS1xx': Permission de$
make: **\* [build/libLMS1xx] Error 128"

Could someone tell me what I am doing wrong and what I need to do to get this sensor working?

Thanks.

**Comment by konradb3** [comment]
Are you sure that you have write permissions in this directory ?
